### ISSUE TITLE
Add PDF usage manual to repository

### ISSUE THREAD

**Issue by tsujamin** [BSidesCbr/BUSSide#1]
It would be good if the manual for the BUSSide available at the conference in physical form were added to the repository as a PDF. 

This would ensure its content would be available alongside the client code and ensure a backup exists should the Infosect Wiki copy be lost.

**Comment by digitalrane** [comment]
I reckon it should be added as the README.md for the repository. Binary formats like PDF get a little gross with git.

I'm going to let Silvio decide what to do with this one. Having it as the README for the repo would allow people to submit fixes/edits to the documentation very easily.

**Comment by BSidesCbr** [comment]
Added PDF manual - printed the wiki page.
