### ISSUE TITLE
No need to wait after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [BSidesCbr/BUSSide#5]
In the file "BUSSide/BUSSide/I2C.ino" the usage of `Wire.requestFrom()` and `Wire.available()` are used in a way as if `Wire.available()` waits for something.
The `Wire.requestFrom()` is blocking, it returns when the I2C transaction on the bus has finished. The `Wire.available()` returns the number of bytes in a buffer. There is no need to wait after the `Wire.requestFrom()`. This is the same for all Arduino Wire compatible libraries.
Explanation: [Common-mistakes#1](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1)

About the function `read_I2C_eeprom()`:
The `ESP.wdtFeed();` is in the while-statement. But the `Wire.available()` and `Wire.read()` are fast. The `Wire.requestFrom()` is the one that takes time.

About the function `I2C_active_scan1()`:
When the `Wire.requestFrom()` does not return 8, the next slaveAddress is tested. The code after that (with the for-statement and the delay) is not really doing something, it falls through that code and executes the `ESP.wdtFeed();` and `numberOfSlaves++;`.

**Comment by BSidesCbr** [comment]
Thank you. The fixes went in the last commit.
