### ISSUE TITLE
Will this work on ESP32?

### ISSUE THREAD

**Issue by joanbono** [BSidesCbr/BUSSide#8]
Just wondering if this will work on NodeMCU style board with WROOM32 chipset, which includes Bluetooth apart from WiFi.

Do you know if it’s compatible?

Thanks!

**Comment by digitalrane** [comment]
I'm not sure it's been tested, and some of the GPIO names may need tweaking - but if it is supported by Arduino is could be made to work. If you have the board already, would be curious to see how you go compiling and uploading it with the ESP32 Arduino core.

**Comment by joanbono** [comment]
I’m waiting for the board but I’ll look into it

**Comment by digitalrane** [comment]
Going to close this for now but happy for a PR if you get it working.
